### ISSUE TITLE
cant render screen

### ISSUE THREAD

**Issue by clutchxzmods** [CreepyOrb924/creepy-salhack#56]
Whenever I open the game with creepy salhack installed it shows a plain dirt screen for a few seconds then crashes.
When I remove salhack my game boots up fine.

WARNING: coremods are present:
  MixinBooter (!mixinbooter-7.1.jar)
  KAMIBlueMixinLoader (kamiblue-2.04.21-3c581c22b.jar)
  MixinLoaderForge (creepy-salhack-2.08.jar)
  SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.1.6-forge-mc1.12.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 4/3/23 10:49 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.GuiScreen.redirect$zkh000$bindTextureHook(GuiScreen.java:2352)
	at net.minecraft.client.gui.GuiScreen.func_146278_c(GuiScreen.java:596)
	at net.minecraft.client.gui.GuiScreen.func_146270_b(GuiScreen.java:586)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:574)
	at net.minecraftforge.fml.client.GuiDupesFound.func_73863_a(GuiDupesFound.java:41)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1462)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

(MixinBooter) Mixins in Stacktrace:
	net.minecraft.client.renderer.EntityRenderer:
		me.earth.earthhack.impl.core.mixins.render.entity.IEntityRenderer (mixins.earth.json)
		baritone.launch.mixins.MixinEntityRenderer (mixins.baritone.json)
		org.kamiblue.client.mixin.client.render.MixinEntityRenderer (mixins.kami.json)
		me.ionar.salhack.mixin.client.MixinEntityRenderer (mixins.salhack.json)
		me.earth.earthhack.impl.core.mixins.render.entity.MixinEntityRenderer (mixins.earth.json)
	net.minecraft.client.gui.GuiScreen:
		me.ionar.salhack.mixin.client.MixinGuiScreen (mixins.salhack.json)
		org.kamiblue.client.mixin.client.gui.MixinGuiScreen (mixins.kami.json)
		me.earth.earthhack.impl.core.mixins.gui.MixinGuiScreen (mixins.earth.json)
		baritone.launch.mixins.MixinGuiScreen (mixins.baritone.json)
	net.minecraft.client.main.Main:
		me.earth.earthhack.impl.core.mixins.MixinMain (mixins.earth.json)
	net.minecraftforge.client.ForgeHooksClient:
		com.supermartijn642.core.mixin.LevelRendererMixin (supermartijn642corelib.mixins.json)
	net.minecraft.client.Minecraft:
		org.kamiblue.client.mixin.client.accessor.AccessorMinecraft (mixins.kami.json)
		me.ionar.salhack.mixin.client.MixinMinecraft (mixins.salhack.json)
		org.kamiblue.client.mixin.client.MixinMinecraft (mixins.kami.json)
		baritone.launch.mixins.MixinMinecraft (mixins.baritone.json)
		me.earth.earthhack.impl.core.mixins.MixinMinecraft (mixins.earth.json)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.gui.GuiScreen.redirect$zkh000$bindTextureHook(GuiScreen.java:2352)
	at net.minecraft.client.gui.GuiScreen.func_146278_c(GuiScreen.java:596)
	at net.minecraft.client.gui.GuiScreen.func_146270_b(GuiScreen.java:586)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:574)
	at net.minecraftforge.fml.client.GuiDupesFound.func_73863_a(GuiDupesFound.java:41)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)

-- Screen render details --
Details:
	Screen name: net.minecraftforge.fml.client.GuiDupesFound
	Mouse location: Scaled: (343, 237). Absolute: (686, 604)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1462)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 154855760 bytes (147 MB) / 1767374848 bytes (1685 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 15 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version           | Source                                        | Signature                                |
	|:----- |:---------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	|       | minecraft              | 1.12.2            | minecraft.jar                                 | None                                     |
	|       | mcp                    | 9.42              | minecraft.jar                                 | None                                     |
	|       | mixinbooter            | 7.1               | minecraft.jar                                 | None                                     |
	|       | FML                    | 8.0.99.99         | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | forge                  | 14.23.5.2860      | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | appleskin              | 1.0.14            | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	|       | clumps                 | 3.1.2             | Clumps-3.1.2.jar                              | None                                     |
	|       | lunatriuscore          | 1.2.0.42          | creepy-salhack-2.08.jar                       | None                                     |
	|       | schematica             | 1.8.0.169         | creepy-salhack-2.08.jar                       | None                                     |
	|       | creepy-salhack         | 2.8               | creepy-salhack-2.08.jar                       | None                                     |
	|       | experiencebugfix       | 1.0.0.0           | ExperienceBugFix-1.12.2-1.0.0.0.jar           | None                                     |
	|       | kamiblue               | 2.04.21-3c581c22b | kamiblue-2.04.21-3c581c22b.jar                | None                                     |
	|       | lunatriuscore          | 1.2.0.42          | LunatriusCore-1.12.2-1.2.0.42-universal.jar   | None                                     |
	|       | schematica             | 1.8.0.169         | Schematica-1.12.2-1.8.0.169-universal.jar     | None                                     |
	|       | supermartijn642corelib | 1.1.6             | supermartijn642corelib-1.1.6-forge-mc1.12.jar | None                                     |

	Loaded coremods (and transformers): 
MixinBooter (!mixinbooter-7.1.jar)
  
KAMIBlueMixinLoader (kamiblue-2.04.21-3c581c22b.jar)
  
MixinLoaderForge (creepy-salhack-2.08.jar)
  
SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.1.6-forge-mc1.12.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.5171' Renderer: 'Intel(R) HD Graphics 4600'
	Launched Version: forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.5171, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: RedInsane8b, SalC1 Pack 1.11 - 1.12.2.zip, mycelium-to-grass.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.5171
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by CreepyOrb924** [comment]
This seems to be an ongoing issue with the Dupe button. I will look at it when I can.
